---
abstract: 'Strawberry + Padre for Win32 builder'
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
build_requires:
  LWP::Online: 1.07
  Test::More: 0.86
  Test::Perl::Dist: 0.202
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Dist-Padre
provides:
  Perl::Dist::Padre:
    file: lib/Perl/Dist/Padre.pm
    version: 0.630
requires:
  File::ShareDir: 1.00
  Perl::Dist::Strawberry: 2.02
  Perl::Dist::WiX: 1.102002
  URI::file: 4.20
  parent: 0.221
  perl: 5.010001
resources:
  IRC: irc://irc.perl.org/#padre
  WebIRC: http://widget.mibbit.com/?server=irc.perl.org&channel=%23padre
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-Padre
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: https://svn.perlide.org/padre/trunk/Perl-Dist-Padre
version: 0.630
