---
abstract: 'Padre Standalone for Win32 (EXPERIMENTAL)'
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  LWP::Online: 1.07
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Dist::Padre
name: Perl-Dist-Padre
no_index:
  directory:
    - inc
    - t
requires:
  Perl::Dist::Strawberry: 1.1114
  Perl::Dist::WiX: 0.192
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#padre
  Web2IRC: http://widget.mibbit.com/?server=irc.perl.org&channel=%23padre
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Perl-Dist-Padre
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: https://svn.perlide.org/padre/trunk/Perl-Dist-Padre
version: 0.260010
